/*
  Text versions of the student picture books, so screen readers (and anyone who
  prefers text) can read the stories. One entry per page, in order; "" for pages
  with no story text. Keyed by the book's folder name in content.js.
  Transcribed from the page images, keeping the students' own wording.
*/
window.BOOK_TEXT = {
  "the-fire-disaster": [
    "",
    "One day, on the Wild Island, there was a robot called Roz. Roz and other robots were on a ship, but there was a storm with strong lightning, which was a problem. They were supposed to be going to the robot factory, but everything changed. CRASH! The glowing, strong lightning was hitting the ship as all the other robots fell into the ocean, and they did not move. However, Roz was the only one who survived.",
    "The next day, Roz found a strange island she had never seen before. \"I wonder what this island is,\" she wondered. Roz landed the ship, and it was sinking down. \"Hello, I am ROZZUM Unit 7134, but you may call me Roz,\" said Roz to the animals, but they did not understand her. Roz wanted to get the animals to understand her, and she also wanted to understand the animals.",
    "Early in the morning, the animals wanted to teach Roz their language. They spent hours trying to teach Roz, and finally, she understood. \"Why don't we build a house?\" asked Roz. \"Yeah!\" shouted the animals. Roz and the animals started to gather some resources for the house, like some wood, some stone and some plants. They started to build the house. After 6 months, they finished the house. \"Finally!\" yelled Fink the fox.",
    "Suddenly, Roz found a mysterious egg in the middle of nowhere. \"Why is this egg alone here?\" Roz asked. Crack! A baby gosling came out from the egg, and Roz didn't want to leave him alone, so she would care for him. Roz needed to give this little goose a name. \"How about I call you Brightbill?\" Roz said as Brightbill jumped up and down when he heard that. \"Okay then, Brightbill,\" said Roz. She put Brightbill on her shoulder, and they went to explore the island more.",
    "Later that afternoon, on the mountains, Roz and Brightbill saw a bridge on top of the ocean. \"That bridge does not look so bad,\" said Roz. Brightbill was trying to flap his wings in the direction of the bridge. \"Shall we try to cross the bridge?\" Roz asked Brightbill. \"Bridge, bridge,\" said Brightbill. Roz started to get closer to the bridge, then she started walking on it to get to the other side. The bridge started to collapse under Roz's feet! She ran, but it was getting worse. Even Brightbill felt scared. She walked carefully and tried to be slow, but luckily, she and Brightbill made it to the other side. \"That was close,\" said Roz.",
    "Before the sun rose, Roz knew that she had to return to the robot factory because she needed more power so that she didn't run out of battery. But she couldn't leave Brightbill alone! Roz got an idea of where to leave Brightbill while she was gone: the bears! She would leave Brightbill with the bears. \"Hi, may I leave Brightbill with you?\" asked Roz. \"I must go to the robot factory.\" \"Sure,\" replied the bear mother.",
    "After Roz left Brightbill with the bears, she went on an airship to make her way to the factory. After a while, Roz finally saw the robot factory, and she landed the airship on the ground. Inside, there were some robots being made, but they were not moving. Roz went to the space where the robots could get more power. \"Mission complete,\" said Roz. She would go back to the island using her airship again.",
    "She saw the island after a while, but with lots of smoke. She knew that she was close, but what could have happened? Roz arrived at the island. She was about to land the airship, but she saw that the island was all covered in bushfire! Instead of landing the airship, she jumped off it. Moments later, she saw that Brightbill was dead in the middle of the fire! \"Brightbill!\" yelled Roz as she crouched to get closer to him. Then, Roz saw that the bears had also died. They were trying their best to save Brightbill, but they didn't make it.",
    "In the middle of the night, Roz saw something unexpected. She saw that three fire dragons were the ones that caused the bushfire. \"Stay away from the island!\" shouted Roz as she got a stick to fight them. Roz tried her best to defeat them. Reader, you might think Roz will lose, but she is a smart robot, even though she sometimes makes mistakes. Next, Roz didn't think about anything, so she did a simple thing that would hopefully work and kill the dragons. She collected some logs so that she could hit the dragons with them. Roz threw the logs, but the dragons dodged them, and they breathed fire at Roz.",
    "Next, Roz was black and her body was broken, but she didn't give up yet. She collected some wood logs and a giant rock. What could Roz be thinking about? She made a lever from the logs and placed the giant rock close to it. CRACK! The rock smacked the dragons, and they fell, then died.\n\nMoments later, the dragons were slowly disappearing, and some animals came out from their shelter to thank Roz. But her body was broken. The animals were trying to fix it with wood. That was their way to thank Roz. \"Thank you for saving my body,\" said Roz happily. Roz and her friends were putting water on the island using watering cans, and they replanted the trees and the plants. The story ends where the robot and her animal friends fix everything and put the fire out on the island, but there will be more stuff coming for them soon.",
    ""
  ],
  "the-cyborg-factory": [
    "",
    "Dear reader, our robot Roz was sent away in the sky in an enormous aircraft because some heavy-duty robots called RECOs came to the island to retrieve her. They all died, but the last one, RECO 3, said more RECOs would come until they retrieved her, right before his death. Later that day, she saw a burdensome storm in the distance.\n\nBOOM! The alabaster airship dramatically plummeted from the sky with Roz still inside, like a droplet falling from the sky.",
    "SPLASH! She fell into the cloudy waters. Suddenly, while she was sinking in the dark waters, she heard a loud whirring sound in the immense sky coming towards her.\n\nThen, a tough hand reached onto her torso. The police helicopters brought the wild robot to a humongous factory, where they cowardly shoved her into a substantial prison with a stone door that was the only way outside.",
    "Next, Roz rapidly punched the brick wall with all her might, hoping for luck. She also got her repairs when she got to the robot lab. \"Let me out!\" Roz commanded. Even though she was chained up with indestructible chains, she could still think of a plan.\n\nSuddenly, when she was just about to give up, her blue, glowing eyes caught the glimmer of something golden. \"I have found a key,\" Roz cheered, \"to this door.\" She opened the grey door, but little did she know that outside was a cyborg ten times her size, carefully patrolling the highly secured robot factory.",
    "As Roz stealthily sprinted down the elongated hallway like a cheetah, as quietly as possible, the massive robot spotted her. Without warning, the momentous, powerful cyborg slammed the ground with his enormous hand. CRASH! A colossal crater formed in the metallic ground.",
    "Roz thought of an idea. She punched a large tube connecting to all the walls because she knew, with her intelligent computer brain, that if she punched it, the whole factory would explode.\n\nAfter the electronic cyborg turned around, Roz ran out of there as fast as she could. When she got outside, the factory collapsed down onto the massive robot. She went on top to check where he was. When Roz saw him, he was scratched and bruised.",
    "Suddenly, a whole flock of geese swiftly flew to Roz. These were not any ordinary geese; they were Brightbill's flock. They reminded her of Brightbill, but she couldn't see him. As she quickly hopped onto one, she could hear something inside the smashed factory. BOOM! Helicopters burst out of the roof and shot at them.",
    "\"Everyone go!\" commanded Loudwing. The flock took off and flew to the island at full speed. KRA-KOOM! Geese bashed into helicopters, making them crash into others. Finally, there were only a few more helicopters in the air. The police helicopters stopped chasing them halfway through the distant journey because they were too afraid to keep going.",
    "When she got there, all the animals were there except for Brightbill. From out of nowhere, Brightbill leaped into her arms for a big hug. \"I'll never leave you again, Ma,\" cried Brightbill. Everyone celebrated by throwing an enormous party. They were finally reunited.",
    ""
  ],
  "the-last-alien": [
    "",
    "BOOM! \"ROZZUM Unit 7134, how are your repairs?\" asked a mysterious voice.\n\n\"G-Good,\" Roz replied. BANG! CRASH! Roz landed in the murky, dark sewer. As she tripped over a huge rock, she got a light scratch. The airship had crashed.\n\nRoz fell into the shallow, dim yet clear water. After she hit the ground, Roz got a massive incision across her body. Roz muttered to herself, \"Disgusting yet interesting.\" She rushed her hand through the misty water.",
    "Roz made herself a wingsuit using rocks, branches, and some syrupy dirt. Roz used these materials to create the wingsuit. She tried to fly out through the maintenance hole. Reader, this somehow worked.\n\nSuddenly, Roz was out in a futuristic, high-contrast city. Beaming rays of light flared out from elevated black towers. Lightning was flashing everywhere. People inside the skyscrapers were screaming at the top of their lungs.",
    "FLASH! A huge strike of lightning struck Roz. Resolutely, Roz landed on a tiny rock. Roz tried to fly; however, her wingsuit had shattered into a million pieces. So, Roz was forced to think of a plan on the spot. She thought as hard as her computer brain could.\n\nI guess I have no choice, Roz thought to herself. Then she jumped into the death pool, which was what Roz thought it was. Roz's computer brain saw a huge spike. Roz emerged in a sleek, newly upgraded robotic form. There was an issue, however: there was a huge tidal wave.",
    "Once she activated her untouched and enhanced form, Roz dug straight through the spike. Unfortunately for Roz, a massive, humongous tidal wave was awaiting her. \"I hope nothing bad is down here,\" Roz whispered to no one in particular.\n\nAfter she bumped off the tough, sandy ground, she was stuck underwater. Roz looked around and spotted a pink alien-octopus hybrid.\n\n\"Hello,\" the unusual hybrid spoke. \"I am Kat.\"\n\n\"Hello, Kat. I am Roz,\" Roz replied.\n\nKat grinned with an uneasy W-shaped mouth. Roz was confused and terrified.",
    "Kat gently pulled out ruby swords, which Roz was confused about why she needed.\n\n\"THIS IS MY CHANCE FOR VENGEANCE! YOUR KIND CUT OFF MY LIMB!\" Kat yelled. Kat's ruby swords flashed through the water like bolts of lightning. Roz was stunned.\n\n\"What do you mean, and why me?\" Roz asked.",
    "The night was pitch-black, and the water glowed like a swarm of neon jellyfish. Kat sat, trying to explain whilst trying to contain her anger.\n\n\"Your kind killed my relatives,\" Kat started. \"And so that's my reason for vengeance,\" Kat finished.\n\nRoz spoke. \"Such weird and horrible origins.\" Roz did not know Kat still wanted revenge.",
    "Kat waited for Roz to become distracted. Once she was, Kat attacked Roz.\n\n\"WHY DID YOU DO THAT?\" Roz screamed with something that felt like agony.\n\n\"DON'T WORRY!\" Kat tried to ease Roz of her pain and misery.\n\nRoz slowly tried to resolve the problem with kindness by asking her what made her do that. Kat refused to explain. This made Roz steal the swords because she could not trust Kat.",
    "Kat looked unsure. \"Fine, I am not so sorry,\" Kat spoke. \"And you are a bad fighter.\" Roz was starting to get mad. \"THAT'S NOT AN APOLOGY!\" Roz yelled. Kat winced with sarcasm. \"Okay, here is a real apology,\" Kat whispered. Roz looked content. \"I am so sorry, Roz. My instincts made me do this. However, tell the robots not to kill me. I am the Last Alien,\" Kat commanded.\n\nRoz accepted this and handed Kat's swords over. However, Kat felt like Roz needed to apologise, so she forced her to.\n\n\"I am sorry, Kat. I overreacted and thought you were trying to be evil, but we both lost a limb today, so it is reasonable,\" Roz said in return.",
    "After they both apologised, they hugged each other. Then Kat went into her hiding place. Kat murmured along the way, \"This isn't over.\"\n\nFor Roz, she had to find Brightbill and reunite with him. That was going to take a while.\n\nRoz slowly woke up from her kind of sleep. She had to float to the top, or in her case, to swim. Whilst her brain blared from her survival instincts, she swam up and up. Roz was in really deep water, which was unfortunate for Roz.",
    "After she rose to the top, Roz was met with her first dose of sunshine in two days, and the robot felt something like joy. Kat was going to follow her; she just had to figure out how. It was spring, flowers were blooming, and the migrations were returning to the island. Roz was going to find Brightbill.\n\nThere were a bunch of messy flocks, but Roz knew her son flew in a perfect V formation and that they went east. Kat, however, thought Roz would fall for her sneaky plan. Though Kat wondered how Roz was able to move. Roz had crafted a new leg using trees, moss, and the same type of syrupy mud that she made her wingsuit with.",
    "Brightbill was also looking for Roz. He had no idea where she had gone after the RECOs' airship had taken her. During the migration, he flew north in hopes of finding his mother. Roz had gone south when she flew out of the sewer hole. Roz could easily have not explored the sewers, but she did.\n\nRoz felt nervous, with what-ifs running in her brain. So, Roz naturally just tried to go to the island. She swam through seas. She ran through meadows because every second mattered. Finally, she found the island, but Brightbill was missing.\n\nRoz got anxious. These were precious seconds, her only chance to see her son. Suddenly, Kat jumped out of a tree and tugged at Roz's head. Brightbill saw his mother, and using his call, he summoned all the animals to fight against Kat, just because Kat was following her.\n\nKat started to scream in a low-pitched voice. The anomaly was starting to get angry. Reader, Kat was an alien, and when she got mad, she started to turn into an anomaly. Kat got distracted by the animals. Roz slowly slipped under Kat's tentacle.",
    "Suddenly, Roz started sliding down a cliff. She saw Brightbill, and she swiftly shot him a glance. Brightbill gracefully landed next to her. The family that everyone thought was separated forever was reunited. Roz felt something like happiness. Brightbill also felt joy.\n\nAnd, reader, that's how Roz and Brightbill were together, reunited forever... for now.",
    ""
  ],
  "the-lost-sewer": [
    "",
    "BOOM!! SMASH!! Early in the morning, a plane crashed in an enormous tropical jungle, and on that plane was Roz, a female automated robot. \"Where am I?\" said Roz. She was on her way to the hotel, and then the plane crashed. She looked around the plane for anyone, but all she could find was broken robot parts.",
    "After that, she took off through the enormous tropical jungle. Roz found a sewer with lots of sewage and waste inside. She went into the sewer seeking help. Then she heard a CLANG! She looked around swiftly. It was a big green sewer monster!",
    "Roz yelled, \"Stay away from me!\" The monster ignored Roz. It went to attack. It charged at the speed of lightning. Roz barely dodged it. It went after her again, but this time she was ready. She heard it howling in anger.",
    "It attacked in rage, but she stood in front of a wall. She dodged the monster, and its head banged into the wall. SMASH!! The monster smashed into the ground. Roz had defeated the sewer monster.",
    "After that, she retraced her steps and made it out. She smelt flowers and fresh air. It smelt horrible in the sewer. She looked around for help. Before she gave up, she had one more look. Then she saw a glow behind a wall of plants.",
    "\"It's a glowing portal!\" screamed Roz. She stepped through the glowing portal.",
    "And on the other side was her island. She looked for her son, Brightbill, and she saw her home. She looked inside. There was Brightbill. She hugged him so tight. Brightbill whispered, \"I missed you, Mama.\" \"I missed you too,\" said Roz.",
    "A day later, Roz went back to the glowing portal. It had disappeared.",
    ""
  ],
  "the-great-molten-escape": [
    "",
    "Clang! Clink! Clang! As Roz's dismantled body moved from side to side in the sleek, white airship, she wondered how Brightbill's new life was going. She thought to herself, \"Is Brightbill okay? Does he need me?\" All these worried thoughts filled her big, computer brain. Roz sighed, \"I hope I return to my usual appearance.\"",
    "BEEEEEEEEEP! The airship was landing. RECO 4 and RECO 5 both delicately, without breaking anything, carried Roz's damaged body onto the robotic foundry floor. RECO 4 placed Roz on the perpetual conveyor belt. WHIRRRRRRRRR! Roz watched the articulated robotic arms work as busily as a bee pollinating a flower. She gently closed her eyes and waited.\n\nMoments later, she woke up with her perfectly rebuilt body. From head to toe, Roz was sparkling clean. As she admired her beautifully refurbished body, she now had the time to act fast and plan an escape.",
    "That night, Roz discreetly tiptoed out of the exit, but in the blink of an eye, Roz noticed two big, bulky sihouettes following her. Roz suddenly realised it was RECO 4 and RECO 5. She slowly turned around and was filled with horror when she saw that they had rifles in their hands. Roz bolted as fast as a lightning bolt, in desperate search of help. BOOM! A dazzling beam of light shot through the air. You see, reader, Roz's new upgrades gave her the speed of light, allowing her to dodge the bullet. Roz now had the time to think of an escape plan to find her way back to her beloved home.",
    "Suddenly, she realised there was a blue iridescent beam of light glowing on the top of her hand. You see, reader, since Roz had been rebuilt, it also meant that she had been recoded. The glowing blue light was telling Roz to activate flight mode. Well, of course, reader, Roz could not help but push it. CLICK! She lost all gravity, and a supersonic jet shot her through the air. Unfortunately, RECO 4 and RECO 5 had taken off using their own airship, but Roz was too fast for them. She blasted through the air as happy as could be. Just in the distance, she saw a big island. The closer she got, the more she wanted to cry tears of joy.",
    "\"At last, I am home,\" she said while landing on the lush, green cliff. \"But how am I ever going to find Brightbill now?\" Roz said with a big sigh.\n\nReader, if you are wondering what happened to RECO 4 and RECO 5, well, they ended up crashing on a different island, which gave Roz a feeling of relief. She began her quest, looking over the colossal island, taking a deep breath, and repeating to herself, 'I have got this. A ROZZUM always completes a task.'",
    "Over the mountain range, at the top of the mountain peak, Roz finally noticed that the air felt more humid, the trees were not as lush or green as they used to be, and there was thick, black smoke surrounding her, making it very hard to see.\n\n\"Mama!\" a familiar voice shrieked.\n\n\"Brightbill?\" she said, sounding surprised.\n\n\"Help me!\" he screamed.\n\n\"I am coming!\" she replied in horror.",
    "A few moments later, she was frozen in fear at the front of a towering cavern, puzzled about whether she should go inside. As she stood inside the sweltering cave, she felt the hot ground shake beneath her metal feet. A shower of glowing embers rained down on her as heavily as big, heavy boulders. The deeper Roz walked inside the cavern, the more she wanted to melt into a puddle.\n\nROAR! A deafening roar echoed through the cavern. Roz took a big, anxious gulp.\n\n\"I hope Brightbill is okay.\"",
    "A sudden burst of energy sent Roz bolting through the cavern in search of Brightbill, and she found him on the other side of the cavern.\n\n\"The only way is through,\" she whispered to herself.\n\nShe heroically walked over to the monster and stood beneath it. Scorching, hot lava dripped from its mouth. SIZZLE! HISSSSS! CRASH! The monster threw Roz to the ground.",
    "\"Mama!\" screamed Brightbill. He flapped his wings as hard as he could as a way of saying, 'STAY AWAY FROM MY MOTHER!'\n\n\"Stay there!\" she scolded weakly. \"You will just get yourself injured!\"\n\nBrightbill ignored her. His mother was the most important thing to him, and he did not want to lose her again.\n\nIn the corner of her eye, she saw a neon red light flashing, and yet again, reader, Roz was tempted, so of course she pushed it...",
    "BOOOM! A beam of golden light struck Roz's torso, turning her body a magnificent gold, but that was not all. She started to grow bigger and bigger and bigger until the cavern started to collapse!\n\nBrightbill was filled with horror, and now he really started to flap his wings as hard as he could.\n\nReader, luckily, Brightbill got to safety, if you were wondering, but the battle had just begun, so he got far away. He knew it was the right thing to do.",
    "As the magma monster and Roz ran for their lives as hard as they could, she realised that since she was a giant, she did not have to run as she would usually run. She did not have to leap over boulders or watch out for lava; her focus was just to escape the collapsing cavern.\n\n\"Well, I am bigger than the magma monster, but I am still not sure how to put an end to this once and for all,\" she said, annoyed.\n\nAt that very moment, an idea sparked in her computer brain.",
    "You see, reader, since the mountain stopped at the ocean, the magma monster could not go any further than the cavern because the salty ocean water would have extinguished the monster, so Roz had the chance to put an end to this disaster. This was her time to act fast.\n\nGUUUUUUUUUUUUUSHH! Roz slapped the water as hard as she could.\n\nWHOOOOOOSH! The magma monster had been extinguished forevermore and sat there like a photo in a picture frame.",
    "\"Mama!\" cried Brightbill.\n\n\"Brightbill!\" replied Roz. \"I thought I lost you. Please do not do that again!\"\n\n\"I will not!\" Brightbill promised.\n\nThey walked out of the pile of rubble, and Roz deactivated giant mode.",
    "As they came out, all the animals were chanting, \"Roz! Roz! Roz!\"\n\nAt last, they were together again, and the island finally felt like home again to Roz.",
    "Although she did not know whether RECO 4 and RECO 5 would ever see her again or try to find her, she wanted to spend all her time with her friends and family.\n\nShe still wondered what her next journey would be.",
    ""
  ],
  "the-way-home": [
    "",
    "One day, Roz was gardening when Brightbill snuck into the science lab and came over to her with an idea to escape together. \"Mum!\" Brightbill whispered. \"Brightbill!\" Roz replied in surprise. \"Let's go home,\" said Brightbill.\n\nThen they escaped without any warning, but suddenly a RECO saw them and tattled to the lab scientist. The lab scientist released the enormous metal mechanical fire dragon robot to chase after and capture Roz.",
    "Eventually, Roz and Brightbill had arrived at the top of the stunning, towering Moogwarty Mountain. \"We should have a rest,\" said Brightbill to Roz. \"Yes! We really should,\" Roz replied. Roz and Brightbill sat beside each other looking at the sunset.\n\nSuddenlly, it became dark like a big, black shadow from the headlands. Soon, an enormous storm struck the mountain. There were blue lightning strikes, and the grourd shook. Roz and Brightbill ran to hide under some trees. Brightbill started to shake in terror. \"Ma, I think we are lost.\" Then suddenly, a deep voice from behind them spoke, \"You are not lost now, Rozzum 7134!\"",
    "Brightbill shrieked as the enormous metal mechanical fire dragon robot stepped out of the shadows nearby. \"Run!\" yelled Roz. \"No, I am not leaving you again!\" Brightbill yelled back.\n\nBefore Roz could look back at Brightbill, he had been swiftly captured by the dragon and the RECO.",
    "\"Mum!\" Brightbill screamed. Roz knew she would get Brightbill back, so Roz quietly jumped on the back of the dragon's tail while no one was looking. Roz stayed still and waited for the moment to sneak in and save Brightbill.\n\nSoon after, the dragon arrived, and Roz saw Brightbill was trapped in an electric metal cage.",
    "\"Ma,\" Brightbill whispered when he saw Roz hiding. But then Roz saw the key to open the cage to save Brightbill.\n\nSuddenly, the molten ground shook, and Roz's feet shook too.\n\nThe dragon had spotted Roz and was happy his plan to capture Roz was going to work!",
    "The fire dragon came BOOM! CRASH! HISS! to Roz, and they started to fight. Roz somersaulted through the air and punched the fire dragon. Roz could see the key to open the cage and save Brightbill. She ran at the fire dragon robot and jumped on his head, knocking it out. The fight was done.",
    "Roz grabbed Brightbill and sprinted out into the sun. \"I should have listened to you,\" said Brightbill. \"It is okay. Luckily, we got out,\" said Roz.\n\nOne day later, Brightbill and Roz saw the island, the home she had always loved since the day she got there off the shipwreck.",
    "The animals cheered with joy, and at nightfall they celebrated the return of Roz and Brightbill.\n\nBrightbill was so happy to be back at their amazing home.\n\nRoz looked out into the sunset and felt weird about all that had happened and thought about all the feelings she was now feeling as a robot.\n\nOne thing for sure, Roz knew that they weren't safe yet.",
    ""
  ],
  "the-elemental-magic": [
    "",
    "SPLASH! SPLASH! The waves washed up Roz the robot. \"Finally!\" Roz said. \"I found the elemental island.\" As Roz looked up at the land, she then remembered she must go through the water and lava island to claim the green magical heartstone, also to find Fink's lost father.",
    "Two weeks earlier, Fink the fox told Roz about his dad, who went to the elemental island before Fink was born, and he never returned. Now listen, reader, Fink's dad was trying to claim the magical green heartstone, as he believed it would make him immortal.\n\nSo, Roz said to Fink, \"I will find what happened to your dad and bring him back to you. Then I will get the heartstone so I can protect everyone.\"\n\n\"Thank you, Roz,\" Fink said in relief. \"Good luck, Roz,\" Fink said.",
    "As Roz was coming over to the elemental island, she crashed. BOOM! Her programming got destroyed. Then Roz kept going on her journey to the elemental island.\n\nListen here, reader, Roz knew she had a long journey ahead of her, but as long as Roz could find Fink's father, she and Fink would have a good friendship.",
    "Roz then headed over to the water and lava island. She then saw 2 dragons. The dragons were made from water and lava. The dragons are probably as strong as a rhino, Roz thought. As soon as the dragons saw Roz, they instantly fired an attack at Roz, but she barely dodged it. Then Roz thought of an idea using her intelligence. Roz knew that fire and water created hard rock, so then she thought if the dragons were made from fire and water, they would be turned to hard rock if they breathed out on each other or if Roz fired an attack at the dragons. So, Roz could get past them to get the magic heartstone. To make her immortal. So, then she could find Fink's dad and bring him back to Fink.",
    "As Roz fought the dragons with all her might, she found that it would be a lot harder than she thought. It would be quite hard to make the dragons breathe fire and water out on each other. As Roz kept trying to get the dragons to breathe fire and water on each other, instead of the dragons getting turned to hard rock, Roz got turned to stone. But due to Roz's strength, she could break out of the hard grey rock with ease. BOOM! The rock went all over the ground. \"Ahh!\" Roz yelled as she broke out of the rock with great strength. She broke out of the rock as if it was a leaf. The dragons did not expect the escape from Roz. While the dragons were confused, Roz noticed it, and then she fired an attack, turning the dragons to stone. \"Yes!\" Roz cheered.",
    "After a while, Roz found the elemental temple where the magic heartstone was. As Roz walked up to get the heartstone, a big, bad RECO with purple flames coming off his back appeared.\n\n\"I am going to get the heartstone first and you are not because you are useless,\" the RECO bragged. \"Then I am going to take you back to the factory and destroy you!!\"\n\nNow listen, reader, the RECO thinks he is the strongest robot in the universe.\n\nRoz then quickly ran up to the heartstone and grabbed it a millisecond before the RECO could grab it.",
    "BAM! Roz implanted the magical heartstone in her chest, making her immortal, and Roz discovered an experimental energy core that could temporarily increase the power of her robotic systems.",
    "After a while, Roz found Fink's father. \"Excuse me, are you Fink's father?\" Roz asked. \"Yes, I am,\" Fink's father replied. \"I have come to rescue you,\" Roz explained. \"Thank you,\" Fink's dad said in relief. \"Come with me,\" Roz said, \"and I can bring you to Fink. He will be happy to see you,\" Roz added. Roz then flew around trying to find Fink. When Roz found Fink, she placed his dad next to Fink. \"Dad,\" Fink said. \"Hi, son,\" Fink's dad replied.",
    ""
  ],
  "the-acid-land": [
    "",
    "WHOOSH! The tsunami had come. All the animals hid except Roz, the worn-down mechanical robot.\n\nShe was running as fast as she could until...\n\nRoz found the magical water of the sea!",
    "She hid in the small crevasse to hide from the big acid monster.\n\nThen she splashed the magical legendary water to see if it would work on the monster. Then Brightbill broke the round glass bottle filled with the magical blue glowing water, and then CRASH! All the water glowed blue like blue fairy lights at nighttime.",
    "The acid burned down all the acid like a molten volcano that had just erupted, taking out the monster too.\n\nThe forest was safe for now... SPLASH! At the beach, there was Roz. She was sitting on her chair, and Brightbill was sitting next to her.",
    "They saw a little bit of green radioactive slime like it was a green disgusting snot bubble!\n\nBut then they heard a little sound, but it was not little at all. BOOM!\n\nThe little uranium acid monsters came back! And the big one too... They fought the monsters with rocks, wood, and Roz's strength because they had no more magical water left in the bottle.",
    "So then, Roz and Brightbill were never seen again to this day...\n\nAt the beach, Brightbill was crying next to Roz's broken, worn-down robot pieces. Brightbill thought Roz was never coming back to life ever again until... the RECOs came back. They wanted to help Roz and bring her back to the island when she was repaired again.",
    "So they brought Roz back to the factory, and Roz said, \"This place looks better than ever!\"\n\nShe was fixed, and she went back to the island.",
    "Days, weeks, months, and even years went by. Roz and Brightbill were still gone until... CRACK! Roz and Brightbill were back.\n\n\"Well, that took a long time to get back to this place,\" Roz said, because Roz and Brightbill were back.",
    "They had a truce to celebrate! Everyone brought food to the truce. They brought berries from the garden, fruits from the tropical trees on the top of the mountain, and way more delicious snacks from the island!\n\nEveryone had a feast. Everyone was so full too. They had a rest for the day. Everyone had the best afternoon ever.",
    ""
  ],
  "the-recos-return": [
    "",
    "There were beeping noises; Roz was in a lab filled with airships. There were computers and mechanical RECOs that were getting upgraded with advanced stuff. Roz started running, trying to find the exit, and RECOs were chasing Roz to rip her apart. They realized that Roz was more intelligent than the RECOs, so Roz started running faster and got to the exit just in time.",
    "She found a computer on a table, and Roz had an idea. Roz started hacking the whole lab, and when she was done, she left the lab and was never found.",
    "When Roz got to the same island where Brightbill and Fink were, the RECOs started chasing Roz.\n\nRoz was angry. She started attacking every single RECO and knocked out all of the RECOs.",
    "Roz started exploring. When Roz explored, she saw the upgraded version of a RECO.\n\nThe RECO was bigger than a house, and then the RECO started chasing Roz.",
    "Roz went into darkness in a tight tunnel where spiders and beetles lived, but the RECO found her.\n\nThe RECO dragged Roz, and Roz's blue eyes turned grey for a split second due to the fight.",
    "Roz got up and started fighting the giant RECO. The RECO started stomping to crush Roz.\n\nRoz was damaged, her face was cracked, and one of her arms went missing. She dodged the stomps and used a powerful punch that destroyed the RECO. Roz's face was cracked, and her arm was also missing.",
    "Roz's friends came to help her find the missing parts of Roz's body. Roz was sad because she was injured and had lost parts.\n\nBrightbill's friend Chitchat was repairing Roz. When Brightbill came, he was happy to see Roz. Roz was surprised because she didn't know that Brightbill was on the island.",
    "Roz said goodbye to her friends and started walking. She was happy to be repaired, but something humongous might come to the island to make a bigger disaster.",
    ""
  ]
};
